### PR TITLE
Set silo final name to parent.artifactId

### PR DESCRIPTION
**Pull request by AlexanderHagenhoff**
@rebuy-de/it-outbound 
@rebuy-de/prp-rebuy-silo-archetype 

I don't want to fail here again ...
aka "we change it to `${project.parent.artifactId}` anyways"

### CODE REVIEW

**Comment by peterpunch** [comment]
👍

**Comment by bjoernhaeuser** [comment]
👍

**Comment by das-vinculum** [comment]
👍

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by svenwltr** [comment]
Isn't the `artifact-id` usually `silo`?

**Pull request merged**
