### PR TITLE
Update silo dependencies

### PR DESCRIPTION
**Pull request by AlexanderHagenhoff**
ping @peterpunch 
PRPs missing?

### CODE REVIEW

**Comment by peterpunch** [comment]
have you tested it?

**Comment by AlexanderHagenhoff** [comment]
mvn clean verify ... yes
all dependencies are found

Tests are ongoing with the new blue-order-import-silo but I don't see any problems right now. 
@peterpunch

**Comment by peterpunch** [comment]
:+1:

**Comment by peterpunch** [comment]
Can U release a new version?

**Comment by AlexanderHagenhoff** [comment]
Yeah, sure

**Comment by jopek** [comment]
:+1:

**Pull request merged**
