### PR TITLE
Update consul client to latest version

### PR DESCRIPTION
**Pull request by das-vinculum**
@rebuy-de/it-platform @peterpunch This updates the consul client to the latest version like requested in https://github.com/rebuy-de/team-platform/issues/80

### CODE REVIEW

**Comment by svenwltr** [comment]
:+1:

**Comment by hendrik-rebuy** [comment]
please replace https://github.com/rebuy-de/rebuy-silo-archetype/blob/master/src/main/resources/archetype-resources/silo/src/main/java/silo/domain/service/ConsulRegistrationService.java
with something like this:
https://github.com/rebuy-de/green-checkout-silo/blob/master/silo/src/main/java/com/rebuy/service/greencheckout/silo/configuration/ConsulConfiguration.java

**Comment by peterpunch** [comment]
:+1:

**Comment by das-vinculum** [comment]
Should work now.

**Comment by peterpunch** [comment]
:+1:

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by das-vinculum** [comment]
@rebuy-de/it-platform @peterpunch Do I need to create another release?

**Pull request merged**
