### PR TITLE
Optimize tests

### PR DESCRIPTION
**Pull request by AlexanderHagenhoff**
@rebuy-de/it-outbound 
@rebuy-de/prp-rebuy-silo-archetype

### CODE REVIEW

**Comment by bjoernhaeuser** [comment]
👍

**Comment by peterpunch** [comment]
👍

**Comment by JanZieglerBerlin** [comment]
You have to adjust the pom for the silo to run unittests properly without the category.

**Comment by AlexanderHagenhoff** [comment]
@JanZieglerBerlin get on my level bru https://github.com/rebuy-de/rebuy-silo-archetype/blob/master/src/main/resources/archetype-resources/silo/pom.xml#L306

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by JanZieglerBerlin** [comment]
👍

**Comment by JanZieglerBerlin** [comment]
Released @AlexanderHagenhoff

**Pull request merged**
