### PR TITLE
Set page resolver one indexed

### PR DESCRIPTION
**Pull request by AlexanderHagenhoff**
A page number of 1 in the request will be considered the first page

@rebuy-de/prp-rebuy-silo-archetype 
@dfreudenberger 
@rebuy-de/it-outbound

### CODE REVIEW

**Comment by das-vinculum** [comment]
Is that the current behavior, I thought we start with 0 everywhere?

**Comment by hendrik-rebuy** [comment]
ah not this again 😭 can't we just define this once and for all and print it out in poster size and hang it over everyones desk?

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by AlexanderHagenhoff** [comment]
@hendrik-rebuy I think it is settled with this PR

**Comment by dfreudenberger** [comment]
👍

**Comment by bjoernhaeuser** [comment]
👍

**Pull request merged**
