### PR TITLE
Fix consul config

### PR DESCRIPTION
**Pull request by poljaric**
@rebuy-de/prp-rebuy-silo-archetype

### CODE REVIEW

**Comment by peterpunch** [comment]
👍

**Comment by svenwltr** [comment]
:+1:

**Comment by das-vinculum** [comment]
👍

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by poljaric** [comment]
@rebuy-de/prp-rebuy-silo-archetype 
Also also added the spring-boot actuator dependency for proper health-check activation.

**Comment by bjoernhaeuser** [comment]
👍

**Pull request merged**
