### PR TITLE
add missing import for remote token services

### PR DESCRIPTION
**Pull request by etwillbefine**
@rebuy-de/prp-rebuy-silo-archetype 

Version will be increased to 5.0.1.

### CODE REVIEW

**Comment by JanZieglerBerlin** [comment]
👎  https://github.com/rebuy-de/rebuy-silo-archetype/pull/50

**Comment by hendrik-rebuy** [comment]
:+1:

**Comment by etux** [comment]
@etwillbefine we were both doing the same! sorry for being faster!

**Comment by hendrik-rebuy** [comment]
@JanZieglerBerlin is right

**Comment by etwillbefine** [comment]
sorry :D

**Pull request closed without merging**
